### ISSUE TITLE
Build Custom Screens

### ISSUE THREAD

**Issue by kevvo15** [kevvo15/Firebase-Project#4]
Create design for home screen, about screen, and other necessary screens. Then ensure that proper navigation between screens is supported.

**Comment by mukesh525** [comment]
@CTOverton @kevvo15 
 Reviewed Master Branch. 
 Have few questions  and suggestion.
 1. It seems package "**set-value**" is used. why we need that in current project?
 2. In header file use **prop types** with default value .
 3. In order to break screen in to reusable component . 
 for Ex- **Header.js** create folder Header=> index.js ,index.css
 every component will have its own style  and one can modify using props

**Comment by kevvo15** [comment]
@mukesh525 @CTOverton 
Thanks for the feedback! I worked mostly on trying to get authentication to work today but I will take this feedback and work on getting it implemented.

1. I used the package "set-value" in an attempt to clear some dependabot alerts that claimed I was using an older version. The issue disappeared after but as I see it is not necessarily being used I can remove that.
2. I'm having a bit of trouble understanding this piece of feedback, what do you mean that I should use prop types with default value?
3. Just to be clear, would it be structured as this: A new folder under components folder called Header, and inside that Header folder have the files for index.js and index.css in there? I see how that would make it easier to make sure every component has its own style since I am using a global style. Thanks!

**Comment by CTOverton** [comment]
@kevvo15 

1. Dependable checks all your code, it could mean that one of the packages you are using is using the `set-value` package. So you may not need to have it yourself but one of your packages needs to update it. In that case it's always a good idea to check to see if your packages need updates. As you commented you should be able to remove it from your dependencies since you don't use it, but its worth checking to see if your other packages need updates so they fix that issue.
2. I think what @mukesh525 is trying to say is that you have a `Header` component that has props available such as `title`, however because it doesn't seem you are using Typescript for this project when you go to implement the `<Header />` component your IDE won't know what properties are available or what is required for your component. I.e. someone could implement `<Header />` without a title and it would just be blank. The [PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) library you can define what properties are allowed for your components, which ones are optional and which are required etc. This helps for projects that don't use TypeScript, however of course if you use TypeScript you don't need to worry about it since you already define the property types.
https://github.com/kevvo15/Firebase-Project/blob/d52232654cb51431e0ad2cb7841818be1d172d03/components/Header.js#L6
3. Refer to the guide I gave you :) https://cheesecakelabs.com/blog/efficient-way-structure-react-native-projects/

**Comment by kevvo15** [comment]
@CTOverton 

1. Gotcha. I'll be sure to check what packages need upgrades accordingly! 
2. I was able to implement TypeScript into this project branch from the guide given by https://reactnative.dev/docs/typescript. However running **yarn tsc** I receive what appears to be a TypeScript error regarding the props of my Header component which states "Binding element 'title' implicitly has 'any' type." This doesn't appear to affect my program during build or run time, but how might I go about fixing this? And more importantly, does simply implementing TypeScript to the project fix the main issue regarding whether my IDE knows what properties are available and/or required for my component? Or would I have to fix this error that came up for that to occur?
3. Thank you! I was considering to address the project structuring issue on a separate branch once these PRs go through to avoid cleaning up the merge conflicts that may arise. I should have started with this guide from the start, that is my bad. 😅😂

**Comment by bwiswell** [comment]
1. Usually, the 'Binding element _ implicitly has 'any' type' error is a result of a missing type definition for the props of a custom component. This issue is related to your second concern about IDE linting - to have auto-completion for what props are available for components, you need to define an `interface` for each component you make. Something like:

`interface HeaderProps = {
  title: string;
  subtitle?: string;
`

indicates that your Header component has a required prop `title` of type `string` and an optional prop `subtitle` of the same type. You would then add this definition to your component:

`
import React, { FunctionComponent} from 'react'
const Header: FunctionComponent<HeaderProps> = (props) => {
  const {
    title,
    subtitle,
    children,
    ...other
  }
}
`

using the `FunctionComponent` type from react will automatically include `children` as an optional prop for any nested components. Otherwise, for a component with no children you can do:

`const Header = (props: HeaderProps): JSX.Element => {

}
`

Once you've done this for each component, your IDE should be able to automatically tell you what props with what types exist for each component. As a bonus, if you follow the documentation style for type interfaces show [here](https://github.com/journeyai/ui-mobile/blob/master/src/components/widgets/CardView/CardView.tsx), most IDEs will be able to pull up the text of the documentation when you start to fill in a value for that prop which can be incredibly useful.
